"""
embed_dashboard.py  --  PlatformIO extra script
Embeds web-dashboard build output into a PROGMEM C++ header.
Usage in platformio.ini:  extra_scripts = pre:scripts/embed_dashboard.py
"""

import gzip
import hashlib
import mimetypes
import os
import re
import sys
from pathlib import Path

# ── Configuration ──────────────────────────────────────────────────────────────

DIST_DIR   = "data/www"
OUT_HEADER = "src/generated/web_ui.h"

ALLOWED_EXTENSIONS = {
    ".html", ".js", ".css", ".ico", ".png", ".svg", ".json", ".woff", ".woff2",
}

GZIP_MIN_SIZE = 150
MAX_FILE_SIZE = 512 * 1024

MIME_OVERRIDES = {
    ".js":    "application/javascript",
    ".mjs":   "application/javascript",
    ".json":  "application/json",
    ".svg":   "image/svg+xml",
    ".ico":   "image/x-icon",
    ".woff":  "font/woff",
    ".woff2": "font/woff2",
}

# ── Helpers ────────────────────────────────────────────────────────────────────

def get_mime(path):
    ext = path.suffix.lower()
    if ext in MIME_OVERRIDES:
        return MIME_OVERRIDES[ext]
    mime, _ = mimetypes.guess_type(str(path))
    return mime or "application/octet-stream"


def symbol_name(url_path):
    s = re.sub(r"[^a-zA-Z0-9]", "_", url_path.lstrip("/"))
    if not s or s[0].isdigit():
        s = "f_" + s
    return s.rstrip("_") or "index"


def maybe_gzip(data):
    if len(data) < GZIP_MIN_SIZE:
        return data, False
    compressed = gzip.compress(data, compresslevel=9)
    if len(compressed) >= len(data):
        return data, False
    return compressed, True


def bytes_to_c_array(data):
    """16 bytes per line, no trailing comma on last line."""
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join("0x{:02x}".format(b) for b in chunk))
    # join with comma+newline; each line except the last gets a comma
    return ",\n".join(lines)


# ── Main generation ────────────────────────────────────────────────────────────

def generate(project_dir_str):
    project_dir = Path(project_dir_str)
    dist_dir    = project_dir / DIST_DIR
    out_header  = project_dir / OUT_HEADER

    if not dist_dir.exists():
        sys.exit(
            "\n[embed_dashboard] ERROR: React build output not found.\n"
            "  Expected: {}\n"
            "  Fix: cd web-dashboard && npm run build\n".format(dist_dir)
        )

    out_header.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    # Build the header in a list of strings to avoid any f-string / .format()
    # interaction with braces inside the binary data.
    out_lines = []

    out_lines.append("// AUTO-GENERATED by scripts/embed_dashboard.py -- DO NOT EDIT")
    out_lines.append("#pragma once")
    out_lines.append("#include <Arduino.h>")
    out_lines.append("#include <pgmspace.h>")
    out_lines.append("")
    out_lines.append("// -- File data -------------------------------------------------------")
    out_lines.append("")

    for path in sorted(dist_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() not in ALLOWED_EXTENSIONS:
            continue

        raw = path.read_bytes()
        if len(raw) > MAX_FILE_SIZE:
            print("[embed_dashboard] SKIP too large ({} B): {}".format(len(raw), path.name),
                  file=sys.stderr)
            continue

        data, is_gz = maybe_gzip(raw)
        url_path    = "/" + path.relative_to(dist_dir).as_posix()
        sym         = symbol_name(url_path)
        mime        = get_mime(path)
        etag        = hashlib.md5(raw).hexdigest()[:8]

        gz_note = ", {} B gzipped".format(len(data)) if is_gz else ""
        # Write the array using explicit string concatenation — no .format() near
        # the hex body, so curly braces in the binary data cannot break anything.
        out_lines.append("// {}  ({} B raw{})".format(url_path, len(raw), gz_note))
        out_lines.append("static const uint8_t _{}[] PROGMEM = {{".format(sym))
        out_lines.append(bytes_to_c_array(data))
        out_lines.append("};")
        out_lines.append("")

        entries.append({"url": url_path, "sym": sym, "size": len(data),
                        "mime": mime, "gzip": is_gz, "etag": etag})

        print("[embed_dashboard]   {:<50s} {:6d} B -> {:6d} B{}".format(
            url_path, len(raw), len(data), " (gz)" if is_gz else ""))

    # Manifest struct
    out_lines.append("// -- Manifest --------------------------------------------------------")
    out_lines.append("")
    out_lines.append("struct WebUIFile {")
    out_lines.append("    const char*    url;")
    out_lines.append("    const uint8_t* data;")
    out_lines.append("    size_t         size;")
    out_lines.append("    const char*    mime;")
    out_lines.append("    bool           gzip;")
    out_lines.append("    const char*    etag;")
    out_lines.append("};")
    out_lines.append("")
    out_lines.append("static const WebUIFile WEB_UI_FILES[] PROGMEM = {")
    for i, e in enumerate(entries):
        comma = "," if i < len(entries) - 1 else ""
        out_lines.append(
            '    {{ "{}", _{}, {}, "{}", {}, "{}" }}{}'.format(
                e["url"], e["sym"], e["size"],
                e["mime"], "true" if e["gzip"] else "false",
                e["etag"], comma
            )
        )
    out_lines.append("};")
    out_lines.append("")
    out_lines.append("static constexpr size_t WEB_UI_FILE_COUNT = {};".format(len(entries)))
    out_lines.append("")

    # Lookup helper — written as plain strings, no .format() with braces
    out_lines.append("// -- Lookup ----------------------------------------------------------")
    out_lines.append("")
    out_lines.append("inline const WebUIFile* webui_find(const char* url) {")
    out_lines.append("    for (size_t i = 0; i < WEB_UI_FILE_COUNT; i++)")
    out_lines.append("        if (strcmp_P(url, (PGM_P)WEB_UI_FILES[i].url) == 0)")
    out_lines.append("            return &WEB_UI_FILES[i];")
    out_lines.append("    // SPA fallback: no extension -> serve index.html")
    out_lines.append("    if (strchr(url, '.') == nullptr)")
    out_lines.append("        for (size_t i = 0; i < WEB_UI_FILE_COUNT; i++)")
    out_lines.append('            if (strcmp_P("/index.html", (PGM_P)WEB_UI_FILES[i].url) == 0)')
    out_lines.append("                return &WEB_UI_FILES[i];")
    out_lines.append("    return nullptr;")
    out_lines.append("}")
    out_lines.append("")

    out_header.write_text("\n".join(out_lines), encoding="utf-8")
    kb = out_header.stat().st_size // 1024
    print("[embed_dashboard] OK  {} ({} files, {} KB)".format(
        out_header.relative_to(project_dir), len(entries), kb))


# ── Entry point ────────────────────────────────────────────────────────────────

try:
    Import("env")                        # noqa: F821  -- SCons builtin
    generate(env.subst("$PROJECT_DIR"))  # noqa: F821
except NameError:
    # Direct invocation: python scripts/embed_dashboard.py
    # Run from the project root.
    generate(os.getcwd())
